update hooks

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,19 +1,14 @@
-#!/bin/sh
-#
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-push".
-
-SCRIPT_DIR=$(dirname "$0")
-SCRIPT_ABS_PATH=`cd "$SCRIPT_DIR"; pwd`
-#Run test
-$SCRIPT_ABS_PATH/../../gradlew test
-if [ $? -eq 0   ]; then
-    echo "test pass"
-else
-    exit [[ $ERROR_INFO =~ "test" ]] && exit 1
+#!/bin/bash
+CMD="./gradlew clean test"
+# Check if we actually have commits to push
+commits=`git log @{u}..`
+if [ -z "$commits" ]; then
+ exit 0
 fi
-
+$CMD
+RESULT=$?
+if [ $RESULT -ne 0 ]; then
+ echo "failed $CMD"
+ exit 1
+fi
+exit 0
