this is a test

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -3,8 +3,8 @@
 CMD="./gradlew ktlint"
 $CMD
 RESULT=$?
-if [ $RESULT -eq 0 ]; then
-    echo "ktlint success"
-else
-    exit [[ $ERROR_INFO =~ "ktlint" ]] && exit 1
+if [ $RESULT -ne 0 ]; then
+ echo "failed $CMD"
+ exit 1
 fi
+exit 0
diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -2,8 +2,8 @@
 CMD="./gradlew test"
 $CMD
 RESULT=$?
-if [ $RESULT -eq 0 ]; then
-    echo "test success"
-else
-    exit [[ $ERROR_INFO =~ "test" ]] && exit 1
+if [ $RESULT -ne 0 ]; then
+ echo "failed $CMD"
+ exit 1
 fi
+exit 0
